---
name: Build Content

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '1,21,41 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        CDZOMBAK_TOKEN: ${{ secrets.CDZOMBAK_TOKEN }}
      run: |-
        python build_content.py
        cat README.md
    - name: Commit and push if changed
      env:
        CDZOMBAK_TOKEN: ${{ secrets.CDZOMBAK_TOKEN }}
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "README-bot"
        git add -A
        git commit -m "update content" || exit 0
        git push

  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Detroit
          filename: github-summary.svg
          base: header, repositories, activity
          base_hireable: true
          base_indepth: true
          repositories: 500
          plugin_lines: yes
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Detroit
          filename: github-sponsor.svg
          base_skip: true
          base: ""
          plugin_sponsors: true
          plugin_sponsors_sections: about,list
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Detroit
          filename: github-langs.svg
          base: ""
          base_indepth: true
          repositories: 500
          plugin_languages: true
          plugin_languages_limit: 12
